Updates in Dockerfile, graphic script ChampSim

diff --git a/testsChampSim/Makefile b/testsChampSim/Makefile
--- a/testsChampSim/Makefile
+++ b/testsChampSim/Makefile
@@ -25,7 +25,7 @@ BIN_CHAMPSIM = $(CHAMPSIM_DIR)/bin/champsim
 #####################################################
 
 WARMUP_INSTRUCTIONS     = 100000000
-SIMULATION_INSTRUCTIONS = 500000000
+SIMULATION_INSTRUCTIONS = 450000000
 
 #####################################################
 
@@ -37,24 +37,49 @@ ifeq ($(strip $(SRC)),)
 	$(error "SRC variable is not defined. Please provide a value for SRC.")
 endif
 
-# Compile the program
-compile: check-src
-	@if [ -f $(CODES_DIR)/$(SRC).cpp ]; then \
-		$(CC) $(CFLAGS) -o $(SRC) $(CODES_DIR)/$(SRC).cpp; \
-	elif [ -f $(CODES_DIR)/$(SRC).c ]; then \
-		$(CPP) $(CFLAGS) -o $(SRC) $(CODES_DIR)/$(SRC).c; \
+# Compile the program for each provided SRC or all if none are specified
+compile:
+	@mkdir -p $(TRACES_DIR)
+	@if [ -z "$(strip $(SRC))" ]; then \
+		echo "SRC is not defined, using all files in $(CODES_DIR)"; \
+		for file in $(CODES_DIR)/*.cpp $(CODES_DIR)/*.c; do \
+			[ -e "$$file" ] || continue; \
+			base_file=$$(basename $$file .cpp); \
+			base_file=$$(basename $$base_file .c); \
+			$(CC) $(CFLAGS) -o $$base_file $$file || $(CPP) $(CFLAGS) -o $$base_file $$file; \
+		done; \
+	else \
+		for src in $(SRC); do \
+			if [ -f $(CODES_DIR)/$$src.cpp ]; then \
+				$(CC) $(CFLAGS) -o $$src $(CODES_DIR)/$$src.cpp; \
+			elif [ -f $(CODES_DIR)/$$src.c ]; then \
+				$(CPP) $(CFLAGS) -o $$src $(CODES_DIR)/$$src.c; \
+			else \
+				echo "Source file for $$src not found in $(CODES_DIR)"; \
+				exit 1; \
+			fi; \
+		done; \
 	fi
 
-convert-pin: check-src compile
+# Convert the program to Pin traces
+convert-pin: compile
 	@mkdir -p $(TRACES_DIR)
-	@if [ -x $(SRC) ]; then \
-		$(PIN) -t $(OBJ-INTEL64) -o $(TRACES_DIR)/$(SRC).champsimtrace  \
-		-t $(SIMULATION_INSTRUCTIONS) -- ./$(SRC); \
+	@if [ -z "$(strip $(SRC))" ]; then \
+		for file in $(CODES_DIR)/*.cpp $(CODES_DIR)/*.c; do \
+			[ -e "$$file" ] || continue; \
+			base_file=$$(basename $$file .cpp); \
+			base_file=$$(basename $$base_file .c); \
+			echo "Converting $$base_file to Pin trace..."; \
+			$(PIN) -t $(OBJ-INTEL64) -o $(TRACES_DIR)/$$base_file.champsimtrace \
+			-t $(SIMULATION_INSTRUCTIONS) -- ./$$base_file; \
+		done; \
 	else \
-		$(PIN) -t $(OBJ-INTEL64) -o $(TRACES_DIR)/$(SRC).champsimtrace  \
-		-t $(SIMULATION_INSTRUCTIONS) -- $(SRC); \
+		for src in $(SRC); do \
+			echo "Converting $$src to Pin trace..."; \
+			$(PIN) -t $(OBJ-INTEL64) -o $(TRACES_DIR)/$$src.champsimtrace \
+			-t $(SIMULATION_INSTRUCTIONS) -- ./$$src; \
+		done; \
 	fi
-	xz -zf $(TRACES_DIR)/$(SRC).champsimtrace
 
 trace: check-src
 	@mkdir -p $(SIMULATION_OUTPUTS)
@@ -76,5 +101,3 @@ clean_outputs:
 clean: clean_outputs
 	find . -type f ! -name '*.cpp' ! -name '*.c' ! -name 'Makefile' \
 	! -name '*.py' ! -name '*.md' ! -name '*.json' -exec rm -f {} +
-
-#python3 champsim.py 32 ../tools/ChampSim traces ../tools/ChampSim/champsim_config.json sim_outputs 10000 5000000000 ; make SRC=cache ; python3 champsim.py 32 ../tools/ChampSim traces ../tools/ChampSim/champsim_config.json sim_outputs 10000 5000000000
